_target_: nuplan.planning.simulation.controller.lqr_cbf_two_stage_controller.LQRCBFTwoStageController
_convert_: 'all'

defaults:
  - tracker: lqr_cbf_tracker
  - motion_model: kinematic_bicycle_model
